/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumItem: typeof import('./src/components/AlbumItem.vue')['default']
    AlbumList: typeof import('./src/components/AlbumList.vue')['default']
    Atropos: typeof import('./src/components/Atropos.vue')['default']
    CategoryItem: typeof import('./src/components/CategoryItem.vue')['default']
    CategoryList: typeof import('./src/components/CategoryList.vue')['default']
  }
}
